Repository monsieurbiz/SyliusCmsPagePlugin, pull requests merged in 2020-11, with the labels that each got.

#6 Add example of page fixture
  src/Fixture/PageFixture.php
  src/Resources/config/sylius/fixtures.yaml
Labels: Status: needs review

#7 Make meta not required in form
  src/Form/Type/PageTranslationType.php
Labels: Status: needs review, quick win

#8 Correct form validations
  composer.json
  src/Form/Type/PageTranslationType.php
  src/Form/Type/PageType.php
  src/Resources/config/services.yaml
  src/Resources/config/sylius/resources.yaml
  src/Resources/config/validation/Page.yaml
  src/Resources/config/validation/PageTranslation.yaml
Labels: Status: needs review

#9 Update Rich Editor to v2.0.0-RC.3
  .github/workflows/recipe.yaml
  composer.json
Labels: Status: needs review, quick win

#10 Better quality checks since Scrutinizer is not running anymore
  Makefile
  composer.json
  phpmd.xml
  phpstan.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/MonsieurBizSyliusCmsPageExtension.php
  src/Fixture/Factory/PageFixtureFactory.php
  src/Fixture/PageFixture.php
  src/Routing/RequestContext.php
  symfony.lock
Labels: Status: needs review, enhancement

#11 Correct minors errors
  Makefile
  README.md
  phpunit.xml.dist
  tests/Application/.env.test
Labels: Status: needs review

#13 Correct README badges
  LICENSE.txt
  README.md
Labels: Status: needs review, quick win

#12 Security check
  .github/workflows/security.yaml
  .scrutinizer.yml
  README.md
Labels: Status: needs review
